name: "IPFS Daemon"
description: "Add-on to run IPFS Daemon"
version: "1.3.3"
slug: "ipfs-daemon"
url: https://github.com/PinoutLTD/ipfs-addon
init: false
startup: services
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/pinoutltd/ipfs-daemon-{arch}
